# Generated by Django 3.2.8 on 2024-03-31 12:37

from django.db import migrations, models
import django.db.models.deletion
import orders_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(verbose_name='Manufacturer')),
                ('model', models.TextField(verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Available device',
                'verbose_name_plural': 'Available devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('addr', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Customer details',
                'verbose_name_plural': "Many customers' details",
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time created')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Last updated')),
                ('status', models.TextField(validators=[orders_app.models.validate_status], verbose_name='Order status')),
                ('coffeemaker_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.coffeemaker', verbose_name='Coffeemaker ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.customer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name': 'Single order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CoffeeMakerInUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(verbose_name='Serial number')),
                ('status', models.TextField(verbose_name='Ownership status')),
                ('coffeemaker_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.coffeemaker', verbose_name='Coffeemaker ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.customer', verbose_name='Owner ID')),
            ],
            options={
                'verbose_name': 'Coffeemaker in use',
                'verbose_name_plural': 'Coffeemakers being used',
                'db_table': 'coffeemakers_in_use',
            },
        ),
    ]
