# Generated by Django 3.2.8 on 2024-03-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_auto_20240331_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeemakerinuse',
            options={'verbose_name': 'Coffeemaker in use', 'verbose_name_plural': 'Coffeemakers currently in use'},
        ),
    ]
