# Generated by Django 3.2.8 on 2024-03-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_alter_coffeemakerinuse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeemaker',
            options={'verbose_name': 'New coffeemaker', 'verbose_name_plural': 'Available coffeemakers'},
        ),
        migrations.AlterModelOptions(
            name='coffeemakerinuse',
            options={'verbose_name': 'New coffeemaker', 'verbose_name_plural': 'Coffeemakers currently in use'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'New customer', 'verbose_name_plural': "Customers' details"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'New order', 'verbose_name_plural': 'Orders'},
        ),
    ]
