# Generated by Django 3.2.8 on 2024-04-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_auto_20240331_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeemakerinuse',
            old_name='coffeemaker_id',
            new_name='coffeemaker',
        ),
        migrations.RenameField(
            model_name='coffeemakerinuse',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='coffeemaker_id',
            new_name='coffeemaker',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('sold', 'sold'), ('returned', 'returned'), ('guarantee repair', 'warranty repair'), ('waiting for payment', 'not payed')], verbose_name='Order status'),
        ),
    ]
