# Generated by Django 3.2.8 on 2024-04-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_auto_20240402_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coffeemaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders_app.coffeemakerinuse', verbose_name='Coffeemaker ID'),
        ),
    ]
