# Generated by Django 3.2.8 on 2024-04-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_alter_order_coffeemaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeemaker',
            options={'verbose_name': 'coffeemaker', 'verbose_name_plural': 'Available coffeemakers'},
        ),
        migrations.AlterModelOptions(
            name='coffeemakerinuse',
            options={'verbose_name': 'Currently in use', 'verbose_name_plural': 'Coffeemakers currently in use'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': "Customers' details"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'Orders'},
        ),
    ]
